### ISSUE TITLE
Clearly state when you need to cargo clean

### ISSUE THREAD

**Issue by Mazwak** [quietboil/sibyl#12]
Hello

Following #9, it would be helpfull to have a notice that you NEED to cargo clean under certain circonstances.

In « Getting Started > Buildding », and in « Notes ».

At least for Windows MSVC, if you build before setting the environment variable.

regards

**Comment by quietboil** [comment]
I decided on a different approach. The updated build script now fails if the target is `msvc` and `OCI_LIB_DIR` is not set. The appropriate message is a part of the failure diagnostics. It is a bit more forgiving for `gnu` targets as those need OCI.DLL. Build scripts scans the PATH for it and would continue if the DLL is found.

Getting Started > [Building](https://quietboil.github.io/sibyl/using.html#building) is updated to point it out. Note also a part about rust-analyzer - if your default toolchain is `msvc` (or `gnu` with OCI.DLL not on the PATH), rust-analyzer needs to be told about `OCI_LIB_DIR`.
