### ISSUE TITLE
How can I get html of book ?

### ISSUE THREAD

**Issue by c5soft** [quietboil/sibyl#13]
I have cloned Sibyl to my local disk and noticed a "book" folder containing reference documents in Markdown format. I am wondering if there is a command that can be used to convert the Markdown files to HTML. How can I achieve this?

**Comment by quietboil** [comment]
Use [mdbook](https://rust-lang.github.io/mdBook/). Once you have the tool, you would run this command from the project's root:
```sh
mdbook build book
```
It'll create `book/pages` where you will find `index.html` which is the file that starts the generated book.

**Comment by c5soft** [comment]
good
