### ISSUE TITLE
One environment and multiple session pools

### ISSUE THREAD

**Issue by baarmaley** [quietboil/sibyl#2]
sibyl: v0.6.2
oci: v21.1

Hello!

I have several oracle db and I want to create a session pool for each of them. 
However, I encountered the following problem, when SessionPool::Drop is called for one of them, the other pools stop working
(get_session method starts return "Err(Oracle(24416, "ORA-24416: Invalid session Poolname was specified."))". 
I simulated this situation in the example below.

```rust
#[tokio::main]
async fn main() {
    let env = sibyl::env().unwrap();

    let session_pool_1 = env.create_session_pool("database_1", "user", "pass", 1, 1, 10).await.unwrap();
    let session_pool_2 = env.create_session_pool("database_2", "user", "pass", 1, 1, 10).await.unwrap();
    {
        let session_pool_3 = env.create_session_pool("database_3", "user", "pass", 1, 1, 10).await.unwrap();
        let _session_3 = session_pool_3.get_session().await.unwrap();
    } // <- call Drop for session_pool_3

    let _session_1 = session_pool_1.get_session().await.unwrap(); // <- Err(Oracle(....))
    let _session_2 = session_pool_2.get_session().await.unwrap();
}
```

I don't understand if it should be like this, or if I'm doing something wrong.
Thanks!

**Comment by quietboil** [comment]
This appears to be yet another OCI quirk in nonblocking mode. The added trace showed that the pool name it complains about is correct. Also, your example (well, somewhat adjusted - awaits removed, etc.) works just fine in blocking mode.

Depending on what you are trying to achieve you might be stuck or you might employ a workaround. If I'm guessing correctly, that "pool 3" is not intended to be used all the time and you want to drop all sessions when the application does not need them. Dropping a pool in nonblocking mode (for now) appears to be a no-go as this somehow corrupts all other pools. The following workaround looks promising (in my tests at least):
* create all you pools "globally"
* create "pool 3" with 0 initial connections:
```rust
let session_pool_3 = env.create_session_pool("database_3", "user", "pass", 0, 1, 10).await.unwrap();
```
* pass pool 3 around until sessions are not needed any longer
* manually "drop" open *sessions* from pool 3:
```rust
session_pool_3.set_session_max_use_count(1)?; // this makes pool drop a connection after only one checkout
for _ in 0..session_pool_3.open_count()? {
    let _sesstion = session_pool_3.get_session().await.unwrap();
}
```
* at this point pool 3 has no open sessions, but the pool itself still exists
* if or when sessions from that pool are needed again, reset "session max use count" to unlimited (0) or some appropriate number:
```rust
session_pool_3.set_session_max_use_count(0).unwrap();
```

Not ideal, but it appears that this way you can ensure that there are no open sessions when you do not need them.
