### ISSUE TITLE
Get "ORA-01406: fetched column value was truncated" when using NLS_CHARACTERSET=TH8TISASCII

### ISSUE THREAD

**Issue by vorrarit** [quietboil/sibyl#6]
My database is using NLS_CHARACTERSET=TH8TISASCII.  While using stmt.query(), I got the error "ORA-01406: fetched column value was truncated".

>
    let stmt = session.prepare("
        select MARITAL_STATUS_NAME,
        from MST_MARITAL_STATUS
        where MARITAL_STATUS_CODE='06'
    ")?;
    let rows = stmt.query("");
    let row = rows.next();
    if let Err(e) = row {
        println!("{}", e);
    }

**Comment by quietboil** [comment]
If you can, please try building your application using the latest (GitHub) version.

**Note** that in your case you would need to provide environment variable `ORACLE_UTF8_CONV_FACTOR` - see [Sibyl User Manual - Character Sets](https://quietboil.github.io/sibyl/encoding.html)

**Comment by vorrarit** [comment]
Yes. It works perfect.
