### ISSUE TITLE
CStr error when trying to build on Oracle Cloud Infrastructure compute instance

### ISSUE THREAD

**Issue by jcaudle** [quietboil/sibyl#8]
When trying to build Sibyl on an OCI compute instance, I'm getting the following compiler error:

```
Compiling sibyl v0.6.10
error[E0308]: mismatched types
  --> /home/opc/.cargo/registry/src/github.com-1ecc6299db9ec823/sibyl-0.6.10/src/err.rs:22:43
   |
22 |         let msg = unsafe { CStr::from_ptr(errmsg_ptr as *const i8) };
   |                            -------------- ^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
   |                            |
   |                            arguments to this function are incorrect
   |
   = note: expected raw pointer `*const u8`
              found raw pointer `*const i8`
note: associated function defined here

For more information about this error, try `rustc --explain E0308`.
error: could not compile `sibyl` due to previous error
```

This seems to be related to rust-lang/rust#100632, but I don't know how it would be fixed to support multiple CPU architectures.

**Comment by quietboil** [comment]
>  how it would be fixed to support multiple CPU architectures

[cuviper](https://github.com/cuviper) actually gave a perfect advice in their [answer](https://github.com/rust-lang/rust/issues/100632#issuecomment-1217256106). I changed the type to `c_char` and it still compiles fine on `x86_64`. I would assume that it would now do the same on `arm`.

I'll release 0.6.11 with that change in a short while. Try it when it becomes available.

**Comment by jcaudle** [comment]
I just was able to build 0.6.11 on my OCI instance. Thank you!
