### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by zhoujun681** [quietboil/sibyl#9]
When i compile i get an error:
**could not find native static library `oci`, perhaps an -L flag is missing?**
how  to solved it?

**Comment by zhoujun681** [comment]
By the way,
I have installed Cmake ,git,visual studio c++ build tools.

**Comment by quietboil** [comment]
Have you followed the [building](https://quietboil.github.io/sibyl/using.html#building) instructions? What you are describing sounds like either a case of the missing/undefined `OCI_LIB_DIR`, or that it is not pointing to the correct directory.

Note that neither `make` nor `Cmake` is used to build Sibyl. Also, `git` presence is entirely orthogonal.

The only caveat in Windows environment that you should be aware of is the selection of the OCI library depending on the platform. For `gnu` variant of rust `OCI_LIB_DIR` would point to the directory with OCI.**dll** and for `msvc` variant - `OCI_LIB_DIR` would point to the directory with OCI.**lib**.

You indicated that you have installed vc++ build tools, so it sounds like you have rust on `msvc`. Note that depending on the Oracle client you might not have `oci.lib` out of the box, so you'd need to download a optional SDK package from Oracle. For example, search for an appropriate "SDK Package" at instant client [downloads](https://www.oracle.com/database/technologies/instant-client/linux-x86-64-downloads.html).

**Comment by zhoujun681** [comment]
Thanks，i did it.I can compile normally examples from github. But the problem persists in my program.

**Comment by zhoujun681** [comment]
Tanks,I succeeded after running the command:cargo clean.
